### ISSUE TITLE
Redis Permission Denied

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/opengpts#123]
On macOS, running `docker compose up` gives me:

```
 ✔ Container redis                Created                                                                                                                                                            0.0s
 ✔ Container opengpts-frontend-1  Created                                                                                                                                                            0.0s
 ✔ Container opengpts-backend-1   Recreated                                                                                                                                                          0.3s
Attaching to backend-1, frontend-1, redis
redis       | chown: changing ownership of '.': Permission denied
redis exited with code 1
```

I resolved this issue by modifying the `docker-compose.yml` to:

```yml
version: "3"

services:
  redis:
    container_name: redis
    image: redislabs/redisearch:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: backend
    ports:
      - "8100:8100" # Backend is accessible on localhost:8100
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      PORT: 8100
      REDIS_URL: "redis://redis:6379"

  frontend:
    build:
      context: frontend
    ports:
      - "5173:5173" # Frontend is accessible on localhost:5173
    environment:
      VITE_BACKEND_URL: "http://backend:8100"

volumes:
  redis-data:

```

I've placed the `redis-data` volume under the `volumes` section at the end of the file and referenced it in the `redis` service.
